<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GUS334E" name="APITest1" tests="6" failures="2" timestamp="30 Jul 2019 06:47:39 GMT" time="13.817" errors="0">
  <testcase name="checkResponseBody" time="0.013" classname="Project.Restassuredproject.testcases.Testcases"/>
  <testcase name="checkResponseBody" time="0.013" classname="Project.Restassuredproject.testcases.Deletemethod"/>
  <testcase name="checkStatusCode" time="0.0" classname="Project.Restassuredproject.testcases.Deletemethod">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
	at Project.Restassuredproject.testcases.Deletemethod.checkStatusCode(Deletemethod.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkStatusCode" time="0.013" classname="Project.Restassuredproject.testcases.Testcases">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
	at Project.Restassuredproject.testcases.Testcases.checkStatusCode(Testcases.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="putcheckpointDetails" time="0.781" classname="Project.Restassuredproject.testcases.Putmethod"/>
  <testcase name="checkResponsetime" time="5.013" classname="Project.Restassuredproject.testcases.Testcases"/>
</testsuite> <!-- APITest1 -->
